# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vK2fOOWAOVSBlrzVV8s1aQ-MBGpavVJy
"""

!pip uninstall -y opencv-python opencv-python-headless opencv-contrib-python >/dev/null 2>&1
!pip install -q opencv-python-headless==4.10.0.84

print("OpenCV installation complete.")

import cv2
import numpy as np
import matplotlib.pyplot as plt

print("OpenCV version:", cv2.__version__)
print("OpenCV path:", cv2.__file__)
print("CascadeClassifier available:", hasattr(cv2, "CascadeClassifier"))

# ============================================
# Face Detection Model
# ============================================

FACE_CASCADE_PATH = (
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

face_detector = cv2.CascadeClassifier(FACE_CASCADE_PATH)

if face_detector.empty():
    raise RuntimeError("Failed to load face detection model")

print("Face detector loaded successfully.")
print("Model path:", FACE_CASCADE_PATH)

# ============================================
# Texture Features
# ============================================

def calculate_texture_features(face):
    """
    Calculate basic texture statistics from a face crop.
    """

    gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

    mean_intensity = float(np.mean(gray))
    std_intensity = float(np.std(gray))

    # Local variation
    laplacian = cv2.Laplacian(gray, cv2.CV_64F)
    laplacian_variance = float(laplacian.var())

    return {
        "mean_intensity": mean_intensity,
        "std_intensity": std_intensity,
        "laplacian_variance": laplacian_variance
    }

# ============================================
# Edge Density
# ============================================

def calculate_edge_density(face):
    """
    Calculate the proportion of pixels
    that belong to detected edges.
    """

    gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

    edges = cv2.Canny(gray, 100, 200)

    edge_pixels = np.count_nonzero(edges)
    total_pixels = edges.size

    edge_density = edge_pixels / total_pixels

    return float(edge_density)

# ============================================
# Noise Estimation
# ============================================

def calculate_noise_features(face):
    """
    Estimate local high-frequency noise
    using a Gaussian-blur residual.
    """

    gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

    blurred = cv2.GaussianBlur(
        gray,
        (5, 5),
        0
    )

    residual = gray.astype(np.float32) - blurred.astype(np.float32)

    noise_std = float(np.std(residual))
    noise_mean = float(np.mean(np.abs(residual)))

    return {
        "noise_std": noise_std,
        "noise_mean": noise_mean
    }

# ============================================
# High Frequency Energy
# ============================================

def calculate_frequency_features(face):
    """
    Estimate high-frequency energy using
    the Laplacian response.
    """

    gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

    laplacian = cv2.Laplacian(
        gray,
        cv2.CV_64F
    )

    high_frequency_energy = float(
        np.mean(np.abs(laplacian))
    )

    return {
        "high_frequency_energy": high_frequency_energy
    }

# ============================================
# Complete Feature Extraction
# ============================================

def extract_forensic_features(face):
    """
    Extract all lightweight visual forensic features.
    """

    features = {}

    # Texture
    texture = calculate_texture_features(face)
    features.update(texture)

    # Edges
    features["edge_density"] = calculate_edge_density(face)

    # Noise
    noise = calculate_noise_features(face)
    features.update(noise)

    # Frequency
    frequency = calculate_frequency_features(face)
    features.update(frequency)

    return features

# ============================================================
# DeepFakeSentry — Recovery Cell
# Reload Step 1 functions after Colab Runtime Restart
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files


# ------------------------------------------------------------
# 1. Face Detection Model
# ------------------------------------------------------------

FACE_CASCADE_PATH = (
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

face_detector = cv2.CascadeClassifier(FACE_CASCADE_PATH)

if face_detector.empty():
    raise RuntimeError("Face detector could not be loaded.")

print("✓ OpenCV loaded")
print("✓ Face detector loaded")


# ------------------------------------------------------------
# 2. Image Loading
# ------------------------------------------------------------

def load_image():

    uploaded = files.upload()

    if not uploaded:
        raise ValueError("No image uploaded.")

    filename = next(iter(uploaded))

    image_bytes = uploaded[filename]

    image_array = np.frombuffer(
        image_bytes,
        np.uint8
    )

    image = cv2.imdecode(
        image_array,
        cv2.IMREAD_COLOR
    )

    if image is None:
        raise ValueError("Could not decode image.")

    return filename, image


# ------------------------------------------------------------
# 3. Face Detection
# ------------------------------------------------------------

def detect_faces(image):

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(60, 60)
    )

    return list(faces)


# ------------------------------------------------------------
# 4. Face Extraction
# ------------------------------------------------------------

def extract_faces(image, faces, padding=20):

    height, width = image.shape[:2]

    face_crops = []

    for (x, y, w, h) in faces:

        x1 = max(0, x - padding)
        y1 = max(0, y - padding)

        x2 = min(width, x + w + padding)
        y2 = min(height, y + h + padding)

        crop = image[y1:y2, x1:x2]

        face_crops.append({
            "bbox": (x, y, w, h),
            "crop": crop,
            "expanded_bbox": (x1, y1, x2, y2)
        })

    return face_crops


# ------------------------------------------------------------
# 5. Feature Functions
# ------------------------------------------------------------

def calculate_texture_features(face):

    gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    )

    mean_intensity = float(
        np.mean(gray)
    )

    std_intensity = float(
        np.std(gray)
    )

    laplacian = cv2.Laplacian(
        gray,
        cv2.CV_64F
    )

    laplacian_variance = float(
        laplacian.var()
    )

    return {
        "mean_intensity": mean_intensity,
        "std_intensity": std_intensity,
        "laplacian_variance": laplacian_variance
    }


def calculate_edge_density(face):

    gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    )

    edges = cv2.Canny(
        gray,
        100,
        200
    )

    edge_pixels = np.count_nonzero(edges)

    total_pixels = edges.size

    edge_density = (
        edge_pixels / total_pixels
    )

    return float(edge_density)


def calculate_noise_features(face):

    gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    )

    blurred = cv2.GaussianBlur(
        gray,
        (5, 5),
        0
    )

    residual = (
        gray.astype(np.float32)
        - blurred.astype(np.float32)
    )

    noise_std = float(
        np.std(residual)
    )

    noise_mean = float(
        np.mean(np.abs(residual))
    )

    return {
        "noise_std": noise_std,
        "noise_mean": noise_mean
    }


def calculate_frequency_features(face):

    gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    )

    laplacian = cv2.Laplacian(
        gray,
        cv2.CV_64F
    )

    high_frequency_energy = float(
        np.mean(np.abs(laplacian))
    )

    return {
        "high_frequency_energy":
            high_frequency_energy
    }


def extract_forensic_features(face):

    features = {}

    features.update(
        calculate_texture_features(face)
    )

    features["edge_density"] = (
        calculate_edge_density(face)
    )

    features.update(
        calculate_noise_features(face)
    )

    features.update(
        calculate_frequency_features(face)
    )

    return features


print("✓ All Step 1 + Step 2 functions loaded")

# ============================================
# DeepFakeSentry — Modern Face Detector Setup
# ============================================

!pip -q install --upgrade mediapipe

# ============================================
# Download Lightweight Face Detection Model
# ============================================

!wget -q -O face_detector.tflite \
https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite

import os

print("Model downloaded:", os.path.exists("face_detector.tflite"))

# ============================================
# MediaPipe Tasks Face Detector
# ============================================

from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import mediapipe as mp
import cv2
import numpy as np

base_options = python.BaseOptions(
    model_asset_path="face_detector.tflite"
)

options = vision.FaceDetectorOptions(
    base_options=base_options,
    min_detection_confidence=0.5
)

face_detector_mp = vision.FaceDetector.create_from_options(
    options
)

print("✓ Modern MediaPipe face detector loaded")

# ============================================
# Face Detection
# ============================================

def detect_faces(image, min_confidence=0.5):
    """
    Detect faces using MediaPipe Face Detector.

    Returns:
        [
            {
                "bbox": (x, y, w, h),
                "confidence": confidence
            }
        ]
    """

    h, w = image.shape[:2]

    # OpenCV BGR -> RGB
    rgb_image = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )

    # NumPy -> MediaPipe Image
    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb_image
    )

    # Run detector
    result = face_detector_mp.detect(mp_image)

    detected_faces = []

    for detection in result.detections:

        confidence = float(
            detection.categories[0].score
        )

        if confidence < min_confidence:
            continue

        bbox = detection.bounding_box

        x = int(bbox.origin_x)
        y = int(bbox.origin_y)

        box_w = int(bbox.width)
        box_h = int(bbox.height)

        # Clamp coordinates
        x = max(0, x)
        y = max(0, y)

        box_w = min(box_w, w - x)
        box_h = min(box_h, h - y)

        if box_w <= 0 or box_h <= 0:
            continue

        detected_faces.append({
            "bbox": (x, y, box_w, box_h),
            "confidence": confidence
        })

    return detected_faces

filename, image = load_image()

faces = detect_faces(
    image,
    min_confidence=0.5
)

print("\nImage:", filename)
print("Faces detected:", len(faces))

for i, face in enumerate(faces):

    print(
        f"Face {i+1}: "
        f"bbox={face['bbox']}, "
        f"confidence={(face['confidence']*100):.3f}"
    )

# ============================================
# Visualize Detected Faces
# ============================================

output = cv2.cvtColor(
    image,
    cv2.COLOR_BGR2RGB
).copy()

for i, face in enumerate(faces):

    x, y, w, h = face["bbox"]
    confidence = face["confidence"]

    cv2.rectangle(
        output,
        (x, y),
        (x + w, y + h),
        (255, 0, 0),
        3
    )

    cv2.putText(
        output,
        f"Face {i+1} ({confidence:.2f})",
        (x, max(25, y - 10)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        (255, 0, 0),
        2
    )

plt.figure(figsize=(10, 7))
plt.imshow(output)
plt.axis("off")
plt.title("face detected")
plt.show()

# ============================================================
# DeepFakeSentry — STEP 3
# Face Boundary / Blending Analysis
# ============================================================

def calculate_boundary_score(image, bbox, border_size=12):
    """
    Compare the face boundary with its surrounding region.

    Returns:
        boundary_score: 0-100
        evidence: dictionary of measurable statistics
    """

    x, y, w, h = bbox

    image_h, image_w = image.shape[:2]

    # --------------------------------------------------------
    # Face region
    # --------------------------------------------------------

    face = image[
        y:y+h,
        x:x+w
    ]

    if face.size == 0:
        return 0.0, {}

    # --------------------------------------------------------
    # Expanded region around face
    # --------------------------------------------------------

    x1 = max(0, x - border_size)
    y1 = max(0, y - border_size)

    x2 = min(image_w, x + w + border_size)
    y2 = min(image_h, y + h + border_size)

    expanded = image[
        y1:y2,
        x1:x2
    ]

    # --------------------------------------------------------
    # Resize face and expanded region
    # --------------------------------------------------------

    face_resized = cv2.resize(
        face,
        (128, 128)
    )

    expanded_resized = cv2.resize(
        expanded,
        (160, 160)
    )

    # --------------------------------------------------------
    # Color statistics
    # --------------------------------------------------------

    face_mean = np.mean(
        face_resized,
        axis=(0, 1)
    )

    outside_mean = np.mean(
        expanded_resized,
        axis=(0, 1)
    )

    color_difference = np.linalg.norm(
        face_mean - outside_mean
    )

    # --------------------------------------------------------
    # Texture statistics
    # --------------------------------------------------------

    face_gray = cv2.cvtColor(
        face_resized,
        cv2.COLOR_BGR2GRAY
    )

    outside_gray = cv2.cvtColor(
        expanded_resized,
        cv2.COLOR_BGR2GRAY
    )

    face_texture = np.std(
        face_gray
    )

    outside_texture = np.std(
        outside_gray
    )

    texture_difference = abs(
        face_texture - outside_texture
    )

    # --------------------------------------------------------
    # Gradient / edge transition
    # --------------------------------------------------------

    face_edges = cv2.Canny(
        face_gray,
        80,
        160
    )

    outside_edges = cv2.Canny(
        outside_gray,
        80,
        160
    )

    face_edge_density = (
        np.count_nonzero(face_edges)
        / face_edges.size
    )

    outside_edge_density = (
        np.count_nonzero(outside_edges)
        / outside_edges.size
    )

    edge_difference = abs(
        face_edge_density -
        outside_edge_density
    )

    # --------------------------------------------------------
    # Normalize individual signals
    # --------------------------------------------------------

    color_signal = np.clip(
        color_difference / 100.0,
        0,
        1
    )

    texture_signal = np.clip(
        texture_difference / 50.0,
        0,
        1
    )

    edge_signal = np.clip(
        edge_difference / 0.25,
        0,
        1
    )

    # --------------------------------------------------------
    # Combined boundary anomaly
    # --------------------------------------------------------

    anomaly = (
        0.45 * color_signal +
        0.35 * texture_signal +
        0.20 * edge_signal
    )

    boundary_score = float(
        np.clip(anomaly * 100, 0, 100)
    )

    evidence = {
        "color_difference": float(color_difference),
        "texture_difference": float(texture_difference),
        "edge_difference": float(edge_difference),
        "color_signal": float(color_signal),
        "texture_signal": float(texture_signal),
        "edge_signal": float(edge_signal)
    }

    return boundary_score, evidence

# ============================================================
# Boundary Analysis Test
# ============================================================

if len(faces) == 0:

    print("No face detected.")

else:

    for i, face_info in enumerate(faces):

        bbox = face_info["bbox"]

        score, evidence = calculate_boundary_score(
            image,
            bbox
        )

        print(f"\n========== FACE {i + 1} ==========")

        print(
            f"Boundary Anomaly Score: "
            f"{score:.2f}/100"
        )

        print("\nEvidence:")

        for key, value in evidence.items():

            print(
                f"{key:22s}: {value:.4f}"
            )

# ============================================================
# Boundary Visualization
# ============================================================

def visualize_boundary(image, bbox, boundary_score):

    output = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    ).copy()

    x, y, w, h = bbox

    # Face box
    cv2.rectangle(
        output,
        (x, y),
        (x + w, y + h),
        (255, 0, 0),
        3
    )

    # Expanded boundary
    padding = 12

    H, W = image.shape[:2]

    x1 = max(0, x - padding)
    y1 = max(0, y - padding)

    x2 = min(W, x + w + padding)
    y2 = min(H, y + h + padding)

    cv2.rectangle(
        output,
        (x1, y1),
        (x2, y2),
        (255, 255, 0),
        2
    )

    # Score
    cv2.putText(
        output,
        f"Boundary Anomaly: {boundary_score:.1f}/100",
        (20, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.9,
        (255, 0, 0),
        2
    )

    plt.figure(figsize=(10, 7))

    plt.imshow(output)
    plt.axis("off")
    plt.title("Face Boundary / Blending Analysis")

    plt.show()

# ============================================================
# DeepFakeSentry — Improved Boundary / Blending Analysis
# ============================================================

def calculate_boundary_score(
    image,
    bbox,
    ring_width=8
):
    """
    Analyze the immediate boundary around a detected face.

    Compares:
        1. Inner face boundary
        2. Outer background boundary

    Returns:
        boundary_score: 0-100
        evidence: measurable statistics
    """

    x, y, w, h = bbox

    H, W = image.shape[:2]

    # --------------------------------------------------------
    # Safety checks
    # --------------------------------------------------------

    if w <= 20 or h <= 20:
        return 0.0, {}

    # --------------------------------------------------------
    # Face boundary coordinates
    # --------------------------------------------------------

    x1 = max(0, x)
    y1 = max(0, y)
    x2 = min(W, x + w)
    y2 = min(H, y + h)

    face = image[y1:y2, x1:x2]

    if face.size == 0:
        return 0.0, {}

    # --------------------------------------------------------
    # Inner boundary
    # --------------------------------------------------------

    rw = min(
        ring_width,
        max(2, w // 10),
        max(2, h // 10)
    )

    inner_top = face[:rw, :]
    inner_bottom = face[-rw:, :]
    inner_left = face[:, :rw]
    inner_right = face[:, -rw:]

    inner_pixels = np.concatenate([
        inner_top.reshape(-1, 3),
        inner_bottom.reshape(-1, 3),
        inner_left.reshape(-1, 3),
        inner_right.reshape(-1, 3)
    ])

    # --------------------------------------------------------
    # Outer boundary
    # --------------------------------------------------------

    ox1 = max(0, x1 - rw)
    oy1 = max(0, y1 - rw)
    ox2 = min(W, x2 + rw)
    oy2 = min(H, y2 + rw)

    outer = image[oy1:oy2, ox1:ox2]

    # Create mask for pixels OUTSIDE the face
    mask = np.ones(
        outer.shape[:2],
        dtype=np.uint8
    )

    # Face position inside expanded region
    fx1 = x1 - ox1
    fy1 = y1 - oy1
    fx2 = x2 - ox1
    fy2 = y2 - oy1

    mask[
        fy1:fy2,
        fx1:fx2
    ] = 0

    outer_pixels = outer[
        mask == 1
    ]

    if len(outer_pixels) == 0:
        return 0.0, {}

    # --------------------------------------------------------
    # Color difference
    # --------------------------------------------------------

    inner_mean = np.mean(
        inner_pixels,
        axis=0
    )

    outer_mean = np.mean(
        outer_pixels,
        axis=0
    )

    color_difference = float(
        np.linalg.norm(
            inner_mean - outer_mean
        )
    )

    # --------------------------------------------------------
    # Texture difference
    # --------------------------------------------------------

    inner_gray = cv2.cvtColor(
        inner_pixels.reshape(-1, 1, 3),
        cv2.COLOR_BGR2GRAY
    ).flatten()

    outer_gray = cv2.cvtColor(
        outer_pixels.reshape(-1, 1, 3),
        cv2.COLOR_BGR2GRAY
    ).flatten()

    inner_texture = float(
        np.std(inner_gray)
    )

    outer_texture = float(
        np.std(outer_gray)
    )

    texture_difference = abs(
        inner_texture -
        outer_texture
    )

    # --------------------------------------------------------
    # Edge discontinuity
    # --------------------------------------------------------

    face_gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    )

    edges = cv2.Canny(
        face_gray,
        60,
        150
    )

    edge_density = (
        np.count_nonzero(edges)
        / edges.size
    )

    # --------------------------------------------------------
    # Normalize signals
    # --------------------------------------------------------

    color_signal = np.clip(
        color_difference / 80.0,
        0,
        1
    )

    texture_signal = np.clip(
        texture_difference / 40.0,
        0,
        1
    )

    edge_signal = np.clip(
        edge_density / 0.20,
        0,
        1
    )

    # --------------------------------------------------------
    # Final boundary anomaly
    # --------------------------------------------------------

    anomaly = (
        0.50 * color_signal +
        0.30 * texture_signal +
        0.20 * edge_signal
    )

    boundary_score = float(
        np.clip(
            anomaly * 100,
            0,
            100
        )
    )

    evidence = {
        "color_difference": color_difference,
        "texture_difference": texture_difference,
        "edge_density": edge_density,
        "color_signal": color_signal,
        "texture_signal": texture_signal,
        "edge_signal": edge_signal
    }

    return boundary_score, evidence

# ============================================================
# Test Improved Boundary Analysis
# ============================================================

if len(faces) == 0:

    print("No face detected.")

else:

    for i, face_info in enumerate(faces):

        bbox = face_info["bbox"]

        score, evidence = calculate_boundary_score(
            image,
            bbox
        )

        print(f"\n========== FACE {i + 1} ==========")

        print(
            f"Boundary Anomaly: {score:.2f}/100"
        )

        print("\nEvidence:")

        for key, value in evidence.items():

            print(
                f"{key:22s}: {value:.4f}"
            )

# ============================================================
# STEP 4 — Image Anomaly Scoring
# ============================================================

def calculate_feature_anomaly_signals(features):
    """
    Convert raw forensic features into normalized
    0-1 anomaly signals.

    These are heuristic signals, NOT probabilities.
    """

    # --------------------------------------------------------
    # Texture signal
    # --------------------------------------------------------

    laplacian = features["laplacian_variance"]

    texture_signal = np.clip(
        abs(np.log1p(laplacian) - np.log1p(300)) / 3.0,
        0,
        1
    )

    # --------------------------------------------------------
    # Noise signal
    # --------------------------------------------------------

    noise = features["noise_std"]

    noise_signal = np.clip(
        abs(noise - 8.0) / 12.0,
        0,
        1
    )

    # --------------------------------------------------------
    # Frequency signal
    # --------------------------------------------------------

    frequency = features["high_frequency_energy"]

    frequency_signal = np.clip(
        abs(frequency - 12.0) / 15.0,
        0,
        1
    )

    # --------------------------------------------------------
    # Edge signal
    # --------------------------------------------------------

    edge_density = features["edge_density"]

    edge_signal = np.clip(
        abs(edge_density - 0.08) / 0.12,
        0,
        1
    )

    return {
        "texture": float(texture_signal),
        "noise": float(noise_signal),
        "frequency": float(frequency_signal),
        "edges": float(edge_signal)
    }

def calculate_image_anomaly_score(
    features,
    boundary_score
):
    """
    Combine multiple visual anomaly signals.

    Returns:
        anomaly_score: 0-100
        component_scores: dictionary
    """

    signals = calculate_feature_anomaly_signals(
        features
    )

    # Convert boundary score from 0-100 -> 0-1
    boundary_signal = boundary_score / 100.0

    # --------------------------------------------------------
    # Weighted combination
    # --------------------------------------------------------

    anomaly = (
        0.25 * boundary_signal +
        0.25 * signals["texture"] +
        0.20 * signals["noise"] +
        0.15 * signals["frequency"] +
        0.15 * signals["edges"]
    )

    anomaly_score = float(
        np.clip(anomaly * 100, 0, 100)
    )

    component_scores = {
        "boundary": boundary_score,
        "texture": signals["texture"] * 100,
        "noise": signals["noise"] * 100,
        "frequency": signals["frequency"] * 100,
        "edges": signals["edges"] * 100
    }

    return anomaly_score, component_scores

def calculate_authenticity_score(anomaly_score):
    """
    Convert anomaly score into a 0-100
    anomaly-based authenticity score.

    Higher authenticity = lower anomaly.
    """

    authenticity_score = 100 - anomaly_score

    return float(
        np.clip(authenticity_score, 0, 100)
    )

def get_authenticity_status(authenticity_score):

    if authenticity_score >= 90:
        return "LIKELY AUTHENTIC"

    elif authenticity_score >= 70:
        return "LOW SUSPICION"

    elif authenticity_score >= 40:
        return "SUSPICIOUS"

    else:
        return "HIGHLY SUSPICIOUS"

# ============================================================
# Complete Image Analysis Test
# ============================================================

for i, face_info in enumerate(faces):

    bbox = face_info["bbox"]

    # Extract face
    face = image[
        bbox[1]:bbox[1] + bbox[3],
        bbox[0]:bbox[0] + bbox[2]
    ]

    # Forensic features
    features = extract_forensic_features(face)

    # Boundary analysis
    boundary_score, boundary_evidence = (
        calculate_boundary_score(
            image,
            bbox
        )
    )

    # Overall anomaly
    anomaly_score, component_scores = (
        calculate_image_anomaly_score(
            features,
            boundary_score
        )
    )

    # Authenticity
    authenticity_score = (
        calculate_authenticity_score(
            anomaly_score
        )
    )

    status = get_authenticity_status(
        authenticity_score
    )

    print("\n")
    print("=" * 55)
    print(f"FACE {i + 1}")
    print("=" * 55)

    print(
        f"Authenticity Score : "
        f"{authenticity_score:.1f}/100"
    )

    print(
        f"Visual Anomaly     : "
        f"{anomaly_score:.1f}/100"
    )

    print(
        f"Status              : "
        f"{status}"
    )

    print("\nDetected Indicators:")

    for name, score in component_scores.items():

        print(
            f"  {name.capitalize():12s}: "
            f"{score:.1f}/100"
        )

# ============================================================
# STEP 5 — Local Suspicious Region Heatmap
# ============================================================

def generate_anomaly_heatmap(face):
    """
    Generate a lightweight visual anomaly map using:
    - local high-frequency response
    - local noise/residual
    - edge response

    Returns:
        heatmap: normalized 0-1 map
    """

    gray = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2GRAY
    ).astype(np.float32)

    # --------------------------------------------------------
    # 1. High-frequency / Laplacian response
    # --------------------------------------------------------

    laplacian = cv2.Laplacian(
        gray,
        cv2.CV_32F
    )

    laplacian_abs = np.abs(laplacian)

    # --------------------------------------------------------
    # 2. Local noise residual
    # --------------------------------------------------------

    blurred = cv2.GaussianBlur(
        gray,
        (5, 5),
        0
    )

    residual = np.abs(
        gray - blurred
    )

    # --------------------------------------------------------
    # 3. Edge response
    # --------------------------------------------------------

    edges = cv2.Canny(
        gray.astype(np.uint8),
        60,
        150
    ).astype(np.float32) / 255.0

    # --------------------------------------------------------
    # Normalize each feature map
    # --------------------------------------------------------

    def normalize_map(data):

        min_val = np.percentile(data, 5)
        max_val = np.percentile(data, 95)

        if max_val - min_val < 1e-6:
            return np.zeros_like(data)

        normalized = (
            data - min_val
        ) / (
            max_val - min_val
        )

        return np.clip(
            normalized,
            0,
            1
        )

    laplacian_map = normalize_map(
        laplacian_abs
    )

    noise_map = normalize_map(
        residual
    )

    edge_map = normalize_map(
        edges
    )

    # --------------------------------------------------------
    # Combined anomaly map
    # --------------------------------------------------------

    heatmap = (
        0.45 * laplacian_map +
        0.35 * noise_map +
        0.20 * edge_map
    )

    heatmap = cv2.GaussianBlur(
        heatmap,
        (7, 7),
        0
    )

    return np.clip(
        heatmap,
        0,
        1
    )

# ============================================================
# Heatmap Visualization
# ============================================================

def visualize_anomaly_heatmap(
    image,
    bbox,
    heatmap,
    alpha=0.45
):
    """
    Overlay anomaly heatmap on the detected face.
    """

    x, y, w, h = bbox

    face = image[
        y:y+h,
        x:x+w
    ]

    if face.size == 0:
        print("Invalid face region.")
        return

    # Convert heatmap to OpenCV colormap
    heatmap_uint8 = (
        heatmap * 255
    ).astype(np.uint8)

    colored_heatmap = cv2.applyColorMap(
        heatmap_uint8,
        cv2.COLORMAP_JET
    )

    # BGR -> RGB
    face_rgb = cv2.cvtColor(
        face,
        cv2.COLOR_BGR2RGB
    )

    heatmap_rgb = cv2.cvtColor(
        colored_heatmap,
        cv2.COLOR_BGR2RGB
    )

    # Overlay
    overlay = cv2.addWeighted(
        face_rgb,
        1 - alpha,
        heatmap_rgb,
        alpha,
        0
    )

    # --------------------------------------------------------
    # Display
    # --------------------------------------------------------

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(face_rgb)
    plt.title("Detected Face")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(heatmap_rgb)
    plt.title("Anomaly Map")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(overlay)
    plt.title("Suspicious Region Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

# ============================================================
# Test Heatmap
# ============================================================

for i, face_info in enumerate(faces):

    bbox = face_info["bbox"]

    x, y, w, h = bbox

    face = image[
        y:y+h,
        x:x+w
    ]

    heatmap = generate_anomaly_heatmap(
        face
    )

    print(f"\nDisplaying heatmap for Face {i + 1}")

    visualize_anomaly_heatmap(
        image,
        bbox,
        heatmap
    )

# ============================================================
# STEP 6 — Pretrained Deepfake Detector
# ============================================================

!pip -q install transformers accelerate hf_xet

# ============================================================
# DeepFakeSentry — Correct SigLIP2 Detector
# ============================================================

import torch
import cv2
import numpy as np

from PIL import Image

from transformers import (
    AutoImageProcessor,
    SiglipForImageClassification
)

MODEL_NAME = "prithivMLmods/open-deepfake-detection"

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

# Image-only processor
processor = AutoImageProcessor.from_pretrained(
    MODEL_NAME
)

# SigLIP image classification model
deepfake_model = SiglipForImageClassification.from_pretrained(
    MODEL_NAME
)

deepfake_model = deepfake_model.to(device)
deepfake_model.eval()

print("✓ Image processor loaded")
print("✓ Deepfake model loaded")

# ============================================================
# Pretrained Deepfake Prediction
# ============================================================

def predict_deepfake(face_image):
    """
    Run pretrained SigLIP2 deepfake classifier.

    Returns:
        fake_score
        real_score
        predicted_label
    """

    # OpenCV BGR -> RGB
    rgb = cv2.cvtColor(
        face_image,
        cv2.COLOR_BGR2RGB
    )

    pil_image = Image.fromarray(
        rgb
    ).convert("RGB")

    # Image preprocessing
    inputs = processor(
        images=pil_image,
        return_tensors="pt"
    )

    # Move tensors to GPU/CPU
    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Inference
    with torch.no_grad():

        outputs = deepfake_model(
            **inputs
        )

        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )[0]

    fake_score = float(
        probabilities[0].cpu()
    )

    real_score = float(
        probabilities[1].cpu()
    )

    label = (
        "FAKE"
        if fake_score >= real_score
        else "REAL"
    )

    return (
        fake_score,
        real_score,
        label
    )

# ============================================================
# Test Pretrained Detector
# ============================================================

if len(faces) == 0:

    print("No face detected.")

else:

    for i, face_info in enumerate(faces):

        x, y, w, h = face_info["bbox"]

        face = image[
            y:y+h,
            x:x+w
        ]

        fake_score, real_score, label = (
            predict_deepfake(face)
        )

        print("\n" + "=" * 50)
        print(f"FACE {i + 1}")
        print("=" * 50)

        print(
            f"Fake Score : {fake_score * 100:.2f}%"
        )

        print(
            f"Real Score : {real_score * 100:.2f}%"
        )

        print(
            f"Prediction : {label}"
        )

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

# Upload video
uploaded = files.upload()

video_path = list(uploaded.keys())[0]

print("Video:", video_path)

# Open video
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    raise ValueError("Could not open video.")

fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

duration = frame_count / fps if fps > 0 else 0

print("\n" + "="*50)
print("VIDEO INFORMATION")
print("="*50)
print(f"Resolution : {width} x {height}")
print(f"FPS        : {fps:.2f}")
print(f"Frames     : {frame_count}")
print(f"Duration   : {duration:.2f} sec")

# Sample approximately 8 frames across the video

num_samples = min(8, frame_count)

sample_indices = np.linspace(
    0,
    frame_count - 1,
    num_samples,
    dtype=int
)

sampled_frames = []

for frame_idx in sample_indices:

    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)

    ret, frame = cap.read()

    if ret:
        timestamp = frame_idx / fps if fps > 0 else 0

        sampled_frames.append({
            "frame_index": frame_idx,
            "timestamp": timestamp,
            "image": frame
        })

cap.release()

print(f"Successfully sampled {len(sampled_frames)} frames.")

fig, axes = plt.subplots(
    2,
    4,
    figsize=(16, 8)
)

for ax, item in zip(axes.flat, sampled_frames):

    frame_rgb = cv2.cvtColor(
        item["image"],
        cv2.COLOR_BGR2RGB
    )

    ax.imshow(frame_rgb)
    ax.set_title(
        f"Frame {item['frame_index']}\n"
        f"{item['timestamp']:.2f}s"
    )
    ax.axis("off")

plt.tight_layout()
plt.show()

def detect_faces_in_frame(frame, min_confidence=0.5):
    """
    Detect faces in a BGR OpenCV frame.
    Returns list of dictionaries containing bbox and confidence.
    """

    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb
    )

    result = face_detector_mp.detect(mp_image)

    faces = []

    for detection in result.detections:

        bbox = detection.bounding_box

        x = max(0, int(bbox.origin_x))
        y = max(0, int(bbox.origin_y))
        w = int(bbox.width)
        h = int(bbox.height)

        # Keep bbox inside image
        h_img, w_img = frame.shape[:2]

        w = min(w, w_img - x)
        h = min(h, h_img - y)

        confidence = float(
            detection.categories[0].score
        )

        if confidence >= min_confidence and w > 0 and h > 0:
            faces.append({
                "bbox": (x, y, w, h),
                "confidence": confidence
            })

    return faces

video_face_results = []

for item in sampled_frames:

    frame = item["image"]

    faces = detect_faces_in_frame(frame)

    video_face_results.append({
        "frame_index": item["frame_index"],
        "timestamp": item["timestamp"],
        "faces": faces
    })

    print(
        f"Frame {item['frame_index']:4d} | "
        f"Time {item['timestamp']:6.2f}s | "
        f"Faces: {len(faces)}"
    )

fig, axes = plt.subplots(
    2, 4,
    figsize=(16, 8)
)

for ax, item, result in zip(
    axes.flat,
    sampled_frames,
    video_face_results
):

    frame = item["image"].copy()

    for face in result["faces"]:

        x, y, w, h = face["bbox"]

        cv2.rectangle(
            frame,
            (x, y),
            (x + w, y + h),
            (0, 255, 0),
            2
        )

        cv2.putText(
            frame,
            f"{face['confidence']:.2f}",
            (x, max(20, y - 5)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (0, 255, 0),
            2
        )

    frame_rgb = cv2.cvtColor(
        frame,
        cv2.COLOR_BGR2RGB
    )

    ax.imshow(frame_rgb)

    ax.set_title(
        f"{item['timestamp']:.2f}s | "
        f"{len(result['faces'])} face(s)"
    )

    ax.axis("off")

plt.tight_layout()
plt.show()

suspicious_timestamps = [
    x for x in temporal_results
    if x["temporal_anomaly"] >= 70
]

print(
    f"Potentially suspicious transitions: "
    f"{len(suspicious_timestamps)}"
)

for item in suspicious_timestamps:

    print(
        f"⚠ {item['timestamp']:.2f}s | "
        f"Anomaly: {item['temporal_anomaly']:.2f}"
    )

def calculate_frame_anomaly(face_result):
    """
    Combines handcrafted forensic signals into a
    heuristic frame-level anomaly score.
    """

    features = face_result["features"]

    # Normalize individual signals
    texture = np.clip(
        abs(features["laplacian_variance"] - 300) / 300 * 100,
        0, 100
    )

    noise = np.clip(
        abs(features["noise_std"] - 8) / 8 * 100,
        0, 100
    )

    frequency = np.clip(
        abs(features["high_frequency_energy"] - 12) / 12 * 100,
        0, 100
    )

    edges = np.clip(
        abs(features["edge_density"] - 0.08) / 0.08 * 100,
        0, 100
    )

    boundary = face_result["boundary_score"]

    anomaly = (
        0.20 * texture +
        0.20 * noise +
        0.15 * frequency +
        0.15 * edges +
        0.30 * boundary
    )

    return float(np.clip(anomaly, 0, 100))

frame_scores = []

for result in video_frame_analysis:

    if len(result["faces"]) == 0:
        continue

    # Largest face
    face = max(
        result["faces"],
        key=lambda f: f["bbox"][2] * f["bbox"][3]
    )

    anomaly = calculate_frame_anomaly(face)

    frame_scores.append({
        "timestamp": result["timestamp"],
        "frame_index": result["frame_index"],
        "anomaly": anomaly,
        "bbox": face["bbox"]
    })

print(f"✓ Analyzed {len(frame_scores)} video frames.")

# Match temporal information approximately by timestamp

final_frame_results = []

for frame in frame_scores:

    spatial_score = frame["anomaly"]

    # Find closest temporal result
    temporal_score = 0

    if len(temporal_results) > 0:

        closest = min(
            temporal_results,
            key=lambda x: abs(
                x["timestamp"] - frame["timestamp"]
            )
        )

        # Only use if reasonably close
        if abs(
            closest["timestamp"] - frame["timestamp"]
        ) < 5:
            temporal_score = closest["temporal_anomaly"]

    # Combine
    combined = (
        0.70 * spatial_score +
        0.30 * temporal_score
    )

    final_frame_results.append({
        **frame,
        "temporal_anomaly": temporal_score,
        "combined_anomaly": float(
            np.clip(combined, 0, 100)
        )
    })

print("✓ Spatial + temporal analysis combined.")

if len(final_frame_results) == 0:

    print("No usable face detections found.")

else:

    scores = np.array([
        x["combined_anomaly"]
        for x in final_frame_results
    ])

    # Robust aggregation:
    # mostly typical behavior + influence from suspicious peaks
    median_score = np.median(scores)
    high_percentile = np.percentile(scores, 90)

    final_anomaly = (
        0.70 * median_score +
        0.30 * high_percentile
    )

    final_anomaly = float(
        np.clip(final_anomaly, 0, 100)
    )

    authenticity = 100 - final_anomaly

    if authenticity >= 70:
        status = "LOW SUSPICION"
    elif authenticity >= 40:
        status = "SUSPICIOUS"
    else:
        status = "HIGHLY SUSPICIOUS"

    print("\n" + "="*60)
    print("        DEEPFAKESENTRY — VIDEO REPORT")
    print("="*60)

    print(f"Authenticity Score : {authenticity:.1f}/100")
    print(f"Anomaly Score      : {final_anomaly:.1f}/100")
    print(f"Assessment         : {status}")

    print("="*60)
    print("NOTE:")
    print(
        "This is a heuristic visual anomaly analysis, "
        "not definitive forensic proof."
    )

timestamps = [
    x["timestamp"]
    for x in final_frame_results
]

combined_scores = [
    x["combined_anomaly"]
    for x in final_frame_results
]

plt.figure(figsize=(12, 5))

plt.plot(
    timestamps,
    combined_scores,
    marker="o"
)

plt.axhline(
    70,
    linestyle="--",
    label="High anomaly"
)

plt.axhline(
    40,
    linestyle="--",
    label="Moderate anomaly"
)

plt.xlabel("Time (seconds)")
plt.ylabel("Combined Anomaly Score")
plt.title("DeepFakeSentry — Video Anomaly Timeline")

plt.ylim(0, 100)
plt.grid(True, alpha=0.3)
plt.legend()

plt.show()

# Sort frames by combined anomaly score
top_suspicious = sorted(
    final_frame_results,
    key=lambda x: x["combined_anomaly"],
    reverse=True
)

# Keep top 3
top_suspicious = top_suspicious[:3]

print("\n" + "="*60)
print("        SUSPICIOUS EVIDENCE FRAMES")
print("="*60)

for i, item in enumerate(top_suspicious, 1):

    print(
        f"{i}. Timestamp: {item['timestamp']:.2f}s | "
        f"Anomaly: {item['combined_anomaly']:.2f}/100"
    )

# Sort frames by combined anomaly score
top_suspicious = sorted(
    final_frame_results,
    key=lambda x: x["combined_anomaly"],
    reverse=True
)

# Keep top 3
top_suspicious = top_suspicious[:3]

print("\n" + "="*60)
print("        SUSPICIOUS EVIDENCE FRAMES")
print("="*60)

for i, item in enumerate(top_suspicious, 1):

    print(
        f"{i}. Timestamp: {item['timestamp']:.2f}s | "
        f"Anomaly: {item['combined_anomaly']:.2f}/100"
    )

fig, axes = plt.subplots(
    1,
    len(top_suspicious),
    figsize=(18, 6)
)

# Handle single-frame case
if len(top_suspicious) == 1:
    axes = [axes]

for ax, item in zip(axes, top_suspicious):

    # Find original sampled frame
    original = next(
        x["image"]
        for x in sampled_frames
        if x["frame_index"] == item["frame_index"]
    )

    frame = original.copy()

    x, y, w, h = item["bbox"]

    cv2.rectangle(
        frame,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        3
    )

    cv2.putText(
        frame,
        f"Anomaly: {item['combined_anomaly']:.1f}",
        (x, max(30, y - 10)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2
    )

    frame_rgb = cv2.cvtColor(
        frame,
        cv2.COLOR_BGR2RGB
    )

    ax.imshow(frame_rgb)

    ax.set_title(
        f"⚠ {item['timestamp']:.2f}s"
    )

    ax.axis("off")

plt.tight_layout()
plt.show()

print("\n" + "="*60)
print("DEEPFAKESENTRY — EVIDENCE SUMMARY")
print("="*60)

for i, item in enumerate(top_suspicious, 1):

    print(f"\nEvidence #{i}")
    print(f"Timestamp          : {item['timestamp']:.2f} sec")
    print(f"Spatial Anomaly    : {item['anomaly']:.2f}/100")
    print(f"Temporal Anomaly   : {item['temporal_anomaly']:.2f}/100")
    print(f"Combined Anomaly   : {item['combined_anomaly']:.2f}/100")

def analyze_video(video_path, sample_count=12):
    """
    DeepFakeSentry video analysis pipeline.

    Returns:
        final_report, frame_results, temporal_results
    """

    # =========================================================
    # 1. OPEN VIDEO
    # =========================================================

    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        raise ValueError("Could not open video.")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    duration = frame_count / fps if fps > 0 else 0

    # =========================================================
    # 2. SAMPLE FRAMES
    # =========================================================

    num_samples = min(sample_count, frame_count)

    sample_indices = np.linspace(
        0,
        frame_count - 1,
        num_samples,
        dtype=int
    )

    sampled_frames = []

    for frame_idx in sample_indices:

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)

        ret, frame = cap.read()

        if ret:

            timestamp = (
                frame_idx / fps
                if fps > 0
                else 0
            )

            sampled_frames.append({
                "frame_index": frame_idx,
                "timestamp": timestamp,
                "image": frame
            })

    cap.release()

    # =========================================================
    # 3. FACE + FORENSIC ANALYSIS
    # =========================================================

    frame_results = []

    for item in sampled_frames:

        frame = item["image"]

        faces = detect_faces_in_frame(frame)

        if len(faces) == 0:
            continue

        # Select largest face
        face_info = max(
            faces,
            key=lambda f: f["bbox"][2] * f["bbox"][3]
        )

        x, y, w, h = face_info["bbox"]

        face_crop = frame[y:y+h, x:x+w]

        if face_crop.size == 0:
            continue

        features = extract_forensic_features(
            face_crop
        )

        boundary_score, boundary_evidence = (
            calculate_boundary_score(
                frame,
                (x, y, w, h)
            )
        )

        face_result = {
            "bbox": (x, y, w, h),
            "confidence": face_info["confidence"],
            "features": features,
            "boundary_score": boundary_score,
            "boundary_evidence": boundary_evidence
        }

        spatial_anomaly = calculate_frame_anomaly(
            face_result
        )

        frame_results.append({
            "frame_index": item["frame_index"],
            "timestamp": item["timestamp"],
            "image": frame,
            "bbox": (x, y, w, h),
            "anomaly": spatial_anomaly
        })

    # =========================================================
    # 4. TEMPORAL ANALYSIS
    # =========================================================

    temporal_results = []

    previous_face = None
    previous_timestamp = None

    for result in frame_results:

        frame = result["image"]

        x, y, w, h = result["bbox"]

        current_face = frame[y:y+h, x:x+w]

        if previous_face is not None:

            temporal = calculate_temporal_difference(
                previous_face,
                current_face
            )

            if temporal is not None:

                temporal_results.append({
                    "timestamp": result["timestamp"],
                    "previous_timestamp": previous_timestamp,
                    "mean_difference": temporal[
                        "mean_difference"
                    ],
                    "high_difference_ratio": temporal[
                        "high_difference_ratio"
                    ]
                })

        previous_face = current_face.copy()
        previous_timestamp = result["timestamp"]

    # Calculate temporal anomaly
    temporal_results = calculate_temporal_anomaly_scores(
        temporal_results
    )

    # =========================================================
    # 5. COMBINE SPATIAL + TEMPORAL
    # =========================================================

    final_frame_results = []

    for frame in frame_results:

        temporal_score = 0

        if temporal_results:

            closest = min(
                temporal_results,
                key=lambda x: abs(
                    x["timestamp"] -
                    frame["timestamp"]
                )
            )

            temporal_score = closest[
                "temporal_anomaly"
            ]

        combined = (
            0.70 * frame["anomaly"] +
            0.30 * temporal_score
        )

        final_frame_results.append({
            **frame,
            "temporal_anomaly": temporal_score,
            "combined_anomaly": float(
                np.clip(combined, 0, 100)
            )
        })

    # =========================================================
    # 6. FINAL VIDEO SCORE
    # =========================================================

    if not final_frame_results:

        return {
            "error": "No faces detected in sampled frames."
        }, [], []

    scores = np.array([
        x["combined_anomaly"]
        for x in final_frame_results
    ])

    median_score = np.median(scores)
    high_percentile = np.percentile(scores, 90)

    final_anomaly = (
        0.70 * median_score +
        0.30 * high_percentile
    )

    final_anomaly = float(
        np.clip(final_anomaly, 0, 100)
    )

    authenticity = 100 - final_anomaly

    if authenticity >= 70:
        status = "LOW SUSPICION"
    elif authenticity >= 40:
        status = "SUSPICIOUS"
    else:
        status = "HIGHLY SUSPICIOUS"

    # =========================================================
    # 7. TOP EVIDENCE
    # =========================================================

    evidence = sorted(
        final_frame_results,
        key=lambda x: x["combined_anomaly"],
        reverse=True
    )[:3]

    final_report = {
        "resolution": f"{width}x{height}",
        "fps": fps,
        "frame_count": frame_count,
        "duration": duration,
        "frames_analyzed": len(final_frame_results),
        "anomaly_score": final_anomaly,
        "authenticity_score": authenticity,
        "status": status,
        "evidence": evidence
    }

    return (
        final_report,
        final_frame_results,
        temporal_results
    )

report, results, temporal = analyze_video(
    video_path,
    sample_count=12
)

print("\n" + "="*60)
print("        DEEPFAKESENTRY")
print("        VIDEO ANALYSIS REPORT")
print("="*60)

if "error" in report:

    print(report["error"])

else:

    print(f"Duration          : {report['duration']:.2f} sec")
    print(f"Frames analyzed   : {report['frames_analyzed']}")
    print(f"Anomaly Score     : {report['anomaly_score']:.1f}/100")
    print(f"Authenticity      : {report['authenticity_score']:.1f}/100")
    print(f"Assessment        : {report['status']}")

    print("\nTop Evidence:")

    for i, item in enumerate(report["evidence"], 1):

        print(
            f"{i}. "
            f"{item['timestamp']:.2f}s → "
            f"Anomaly {item['combined_anomaly']:.1f}"
        )

print("="*60)

!pip install -q gradio

!pip install -q gradio

import gradio as gr
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import traceback


def portal_analyze(file):

    try:
        if file is None:
            return (
                "## ⚠️ No file uploaded\n\n"
                "Please upload an image or video."
            ), None, None

        path = file

        # =========================
        # VIDEO
        # =========================
        if path.lower().endswith(
            (".mp4", ".avi", ".mov", ".mkv")
        ):

            report, results, temporal = analyze_video(
                path,
                sample_count=12
            )

            if "error" in report:
                return (
                    f"## ❌ Analysis Error\n\n"
                    f"{report['error']}",
                    None,
                    None
                )

            # -------- Evidence image --------
            evidence_img = None

            if report.get("evidence"):

                item = report["evidence"][0]
                frame = item["image"].copy()

                x, y, w, h = item["bbox"]

                cv2.rectangle(
                    frame,
                    (x, y),
                    (x+w, y+h),
                    (0, 255, 0),
                    3
                )

                cv2.putText(
                    frame,
                    f"Anomaly: {item['combined_anomaly']:.1f}",
                    (x, max(30, y-10)),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.8,
                    (0, 255, 0),
                    2
                )

                evidence_img = cv2.cvtColor(
                    frame,
                    cv2.COLOR_BGR2RGB
                )

            # -------- Timeline --------
            timeline_img = None

            if results:

                times = [
                    x["timestamp"]
                    for x in results
                ]

                scores = [
                    x["combined_anomaly"]
                    for x in results
                ]

                fig = plt.figure(figsize=(10, 4))

                plt.plot(
                    times,
                    scores,
                    marker="o"
                )

                plt.axhline(
                    70,
                    linestyle="--",
                    label="High anomaly"
                )

                plt.axhline(
                    40,
                    linestyle="--",
                    label="Moderate anomaly"
                )

                plt.xlabel("Timestamp (seconds)")
                plt.ylabel("Anomaly Score")
                plt.title(
                    "DeepFakeSentry — Temporal Analysis"
                )

                plt.ylim(0, 100)
                plt.grid(alpha=0.3)
                plt.legend()

                fig.canvas.draw()

                timeline_img = np.asarray(
                    fig.canvas.buffer_rgba()
                )[:, :, :3]

                plt.close(fig)

            # -------- Report --------
            report_text = f"""
# 🛡️ DeepFakeSentry

### Visual Media Authenticity Analysis

---

## 🎯 Authenticity Score

# **{report['authenticity_score']:.1f} / 100**

### Assessment
**{report['status']}**

---

## 🔬 Analysis Summary

| Metric | Value |
|---|---:|
| Duration | {report['duration']:.2f} sec |
| FPS | {report['fps']:.2f} |
| Total Frames | {report['frame_count']} |
| Frames Analyzed | {report['frames_analyzed']} |
| Anomaly Score | {report['anomaly_score']:.1f}/100 |

---

## ⚠️ Suspicious Evidence

"""

            for i, item in enumerate(
                report["evidence"], 1
            ):

                report_text += (
                    f"**Evidence {i}:** "
                    f"`{item['timestamp']:.2f}s`  \n"
                    f"- Spatial anomaly: "
                    f"`{item['anomaly']:.1f}/100`  \n"
                    f"- Temporal anomaly: "
                    f"`{item['temporal_anomaly']:.1f}/100`  \n"
                    f"- Combined anomaly: "
                    f"`{item['combined_anomaly']:.1f}/100`\n\n"
                )

            report_text += """
---

### ℹ️ Disclaimer

This prototype detects **visual anomalies associated
with manipulated media**. It is not definitive forensic
proof of whether a video is AI-generated.

**Audio analysis is not included.**
"""

            return (
                report_text,
                evidence_img,
                timeline_img
            )

        # =========================
        # IMAGE
        # =========================
        elif path.lower().endswith(
            (".jpg", ".jpeg", ".png", ".webp")
        ):

            return (
                """
# 🛡️ DeepFakeSentry

## Image Analysis

Image analysis is available through the existing
image pipeline.

The video portal is currently connected to the
working video analysis pipeline.
""",
                None,
                None
            )

        else:

            return (
                "## ❌ Unsupported file\n\n"
                "Use MP4, AVI, MOV, MKV, JPG, JPEG, PNG or WEBP.",
                None,
                None
            )

    except Exception as e:

        traceback.print_exc()

        return (
            f"""
# ❌ Analysis Failed

**{type(e).__name__}:** `{str(e)}`

Check the Colab output for the full traceback.
""",
            None,
            None
        )


# ============================================================
# PORTAL UI
# ============================================================

css = """
.gradio-container {
    max-width: 1200px !important;
}

#title {
    text-align: center;
}

#subtitle {
    text-align: center;
    opacity: 0.75;
}

#analyze {
    height: 55px;
    font-size: 18px;
    font-weight: bold;
}
"""


with gr.Blocks(
    title="DeepFakeSentry",
    css=css,
    theme=gr.themes.Soft()
) as portal:

    gr.Markdown(
        """
# 🛡️ DeepFakeSentry
<div id="subtitle">

### AI-Powered Visual Media Authenticity Analysis

**Image + Video • Face Forensics • Temporal Analysis**

</div>
"""
    )

    gr.Markdown("---")

    with gr.Row():

        with gr.Column(scale=1):

            file_input = gr.File(
                label="📁 Upload Image / Video",
                file_types=[
                    ".mp4",
                    ".avi",
                    ".mov",
                    ".mkv",
                    ".jpg",
                    ".jpeg",
                    ".png",
                    ".webp"
                ],
                type="filepath"
            )

            analyze_button = gr.Button(
                "🔍 ANALYZE MEDIA",
                variant="primary",
                elem_id="analyze"
            )

            gr.Markdown(
                """
**Supported:** MP4, AVI, MOV, MKV, JPG, PNG, WEBP

**Analysis:** Visual only — no audio processing.
"""
            )

        with gr.Column(scale=2):

            report_output = gr.Markdown(
                label="Analysis Report"
            )

    gr.Markdown("---")

    with gr.Row():

        evidence_output = gr.Image(
            label="⚠️ Highest Anomaly Evidence",
            type="numpy"
        )

        timeline_output = gr.Image(
            label="📈 Temporal Anomaly Timeline",
            type="numpy"
        )

    analyze_button.click(
        fn=portal_analyze,
        inputs=file_input,
        outputs=[
            report_output,
            evidence_output,
            timeline_output
        ]
    )


portal.launch(
    share=True,
    debug=True,
    show_error=True
)

